TARGET  := accessws.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -lev -ljansson -lmpdec -lrdkafka -lz -lhiredis -lcurl -lssl -lcrypto -lcrypto -Wl,-Bdynamic -lm -lpthread -ldl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lldap -llber -lrtmp -lidn
include ../makefile.inc
