version: '3.7'

services:
  mysql:
    image: liupeng0518/mysql:5.7-arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viabtc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

  redis-master:
    image: redis:3.2
    command: redis-server
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:3.2
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-sentinel-1:
    image: redis:3.2
    command: redis-sentinel /redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis/sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave

  redis-sentinel-2:
    image: redis:3.2
    command: redis-sentinel /redis/sentinel.conf
    ports:
      - "26382:26379"
    volumes:
      - ./redis/sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave

  redis-sentinel-3:
    image: redis:3.2
    command: redis-sentinel /redis/sentinel.conf
    ports:
      - "26383:26379"
    volumes:
      - ./redis/sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave

volumes:
  mysql_data: